export enum ESimulationRoomButtonId {
    BACK_HOME_BTN,
    CAMERA_BTN,
    TEXT_BTN,
    HDRIs_ASSETS_BTN,
    GLTFs_ASSETS_BTN,
    SPECIAL_EFFECT_BTN,
    MESHES_BTN,
    LIGHT_BTN,
    SHARING_BTN,
    MENU_CLOSING_BTN,
}
